### ISSUE TITLE
`captive_portal` not supported for RP2040

### ISSUE THREAD

**Issue by magnussommarsjo** [magnussommarsjo/pico-dht#2]
Missing functionality fro `captive_portal` for the Raspberry pi pico (RP2040).
Nothing really to do about it but to wait for support or to change board to an `esp32`.

```yaml

  # Enable fallback hotspot in case wifi connection fails
wifi:
  ...
  ap: {}

# This is used to configure the device when it is not connected to WiFi
# You can use this to set the WiFi credentials
# or to set the name of the device
captive_portal:

```
